# to use the automation.yml, this rest_command must be defined in homeassistant/configuration.yml
# update the url to match the IP address of your NowPlayingDisplay server
rest_command:
  update_now_playing:
    url: "http://x.x.x.x:5432/update-now-playing"
    method: POST
    content_type: "application/json"
    payload: '{"album": "{{ album }}", "artist": {{ artist | to_json }}, "title": "{{ title }}", "duration": "{{ duration }}", "elapsed": "{{ elapsed }}", "state": "{{ state }}", "npclient": "{{ npclient }}"}'
